version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: reddit_clone_db
    environment:
      POSTGRES_USER: redditcloneuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redditclonedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring-reddit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit_clone_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/redditclonedb
      SPRING_DATASOURCE_USERNAME: redditcloneuser
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
