version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: reddit_clone_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: redditclonedb
      MYSQL_USER: redditcloneuser
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  spring-reddit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit_clone_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/redditclonedb
      SPRING_DATASOURCE_USERNAME: redditcloneuser
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
